### PR TITLE
Add UpdateExpiration method in order to override cookie expiration.

### PR DESCRIPTION
**Pull request by clems4ever**
In some cases it might be legitimate to override the cookie expiration. For
instance, in an authentication workflow, one might want to check the
"Remember me" option and in that case the session cookie should not expire
anymore while by default all new cookies should inherit from the default
configuration.

### CODE REVIEW

**Comment by savsgio** [comment]
Your change will regenerate session not update the current cookie expiration.

Please see: https://github.com/fasthttp/session/blob/master/types.go#L20.

**Comment by clems4ever** [comment]
Hello @savsgio , you are right, I will improve my PR to keep the same cookie value but with a different expiration date. Thanks.

**Comment by clems4ever** [comment]
It's done.

**Comment by savsgio** [comment]
if you don't need expire the cookie in browser, set cookie expiration to `0` in your session configuration (https://github.com/fasthttp/session/blob/master/types.go#L22).

Also, i found a bug in `session.Get(...)`, because `s.setHTTPValues(ctx, sessionID)` must be call always, not just when session is not found.

**Comment by savsgio** [comment]
i will fix that.

**Comment by clems4ever** [comment]
Yep, setting expires to 0 is exactly what I do for a given cookie now using UpdateExpires.

Ok for the bug, I indeed see your PR.

**Comment by savsgio** [comment]
Nice!

Please, close this PR.

**Comment by clems4ever** [comment]
Thank you very much for having considered that PR :). I need it for this project: https://github.com/clems4ever/authelia. I'm rewriting it in Go.

**Comment by clems4ever** [comment]
Is it expected that it has not been merged before closing?

**Comment by savsgio** [comment]
Oh! don't worry, this PR has not merged

**Comment by clems4ever** [comment]
Sorry, I did not understand. Will it be merged at some point?

**Comment by savsgio** [comment]
It's not necessary to merge your PR, because to not expire cookie and session you must set Expires option in configuration to 0.

If you need update expiration of cookie (and  session), it's more appropriate regenerate a session id.

**Comment by clems4ever** [comment]
This does not work out in my case. I want to be able to have two kind of cookies, some with expiration 0 and some with a given expiration E strictly greater than 0. How would you do without this PR?

The use case is the following: for most authenticated users, the cookies have expiration E (1 hour or so for security reasons) that is set during configuration but some users want to be remembered and so they want their cookie not to expire anymore. For them, when they tick the check, I want to generate a new cookie (or update their current cookie whatever) but this time with an expiration of 0 (which is different from the expiration E set during the configuration phase).

What do you think?

**Comment by savsgio** [comment]
mmmm, it's ok, I already understand what you mean.

Now, if you change the cookie expiration to another different expiration of session in backend, you could save cookie indefinitely, but in server the session will expire, and the next request not find their session, because it will not exist.

I think, it's better use expiration into particular session id and not in general level.
This way allow set a specific expiration to each sessions.

I will accept your PR if you want to do it.

**Comment by clems4ever** [comment]
You're right, I did not think the session would expire in the provider... I agree that it would be better to have an expiration per session instead of a global one and that would totally suit my needs
I will work on that and propose something in a new PR.

Quick question though, do you want to keep the global expiration config to be backward compatible or should I just drop it?

**Comment by savsgio** [comment]
Ok, i will review your changes.

For the moment, better keep `Config.Expires`.

**Comment by savsgio** [comment]
I prefer the global expiration in configuration, save it in each sessions, and update expiration if you want to expecific session.

**Comment by clems4ever** [comment]
We don't really need to save the expiration in the Session instance IMHO unless one would like to query the expiration for a given cookie (I don't need it in my case).

So what I propose is to keep my PR but I need to make sure the provider also refreshes the session lifetime accordingly. Would that be ok?

**Pull request closed without merging**
